services:
    odiseo_sylius_report_plugin.data_fetcher:
        class: Odiseo\SyliusReportPlugin\DataFetcher\DelegatingDataFetcher
        public: true
        arguments: ['@odiseo_sylius_report_plugin.registry.data_fetcher']

    odiseo_sylius_report_plugin.data_fetcher.user_registration:
        class: Odiseo\SyliusReportPlugin\DataFetcher\UserRegistrationDataFetcher
        arguments: ['@odiseo_sylius_report_plugin.filter.query_filter', '%sylius.model.shop_user.class%']
        tags:
            - { name: odiseo_sylius_report_plugin.data_fetcher, fetcher: odiseo_sylius_report_plugin_data_fetcher_user_registration, label: "odiseo_sylius_report_plugin.data_fetcher.user_registration" }

    odiseo_sylius_report_plugin.data_fetcher.sales_total:
        class: Odiseo\SyliusReportPlugin\DataFetcher\SalesTotalDataFetcher
        arguments: ['@odiseo_sylius_report_plugin.filter.query_filter', '%sylius.model.order.class%']
        tags:
            - { name: odiseo_sylius_report_plugin.data_fetcher, fetcher: odiseo_sylius_report_plugin_data_fetcher_sales_total, label: "odiseo_sylius_report_plugin.data_fetcher.sales_total" }

    odiseo_sylius_report_plugin.data_fetcher.number_of_orders:
        class: Odiseo\SyliusReportPlugin\DataFetcher\NumberOfOrdersDataFetcher
        arguments: ['@odiseo_sylius_report_plugin.filter.query_filter', '%sylius.model.order.class%']
        tags:
            - { name: odiseo_sylius_report_plugin.data_fetcher, fetcher: odiseo_sylius_report_plugin_data_fetcher_number_of_orders, label: "odiseo_sylius_report_plugin.data_fetcher.number_of_orders" }

    odiseo_sylius_report_plugin.data_fetcher.shipments_total:
        class: Odiseo\SyliusReportPlugin\DataFetcher\ShipmentsTotalDataFetcher
        arguments: ['@odiseo_sylius_report_plugin.filter.query_filter', '%sylius.model.order.class%']
        tags:
            - { name: odiseo_sylius_report_plugin.data_fetcher, fetcher: odiseo_sylius_report_plugin_data_fetcher_shipments_total, label: "odiseo_sylius_report_plugin.data_fetcher.shipments_total" }
